export default {
  logIn: 'Log In',
  pleaseSign_inAccount: 'Please sign in to your existing account',
  email: 'Email',
  password: 'Password',
  sendCode: 'Send Code',
  forgotPassword: 'Forgot Password',
  signUp: 'Sign Up',
  rememberMe: 'Remember me',
  Verification: 'Verification',
  weSentEmail: 'We have sent a code to your email',
  resend: 'Resend',
  code: 'Code',
  verify: 'Verify',
  doHaveAccount: 'Don’t have an account?',
  or: 'Or',
  reTypePassword: 'Re-Type Password',
  pleaseSignUpStarted: 'Please sign up to get started',
  openRestaurants: 'Open Restaurants',
  free: 'Free',
  restaurantView: 'Restaurant View',
  addToCart: 'Add to Cart',
  cart: 'Cart',
  checkout: 'CheckOut',
  totalAmount: 'Total Amount',
  youSuccessfully: 'You successfully maked a payment,enjoy our service!',
  congratulations: 'Congratulations!',
};
